server:
  port: 3315
  servlet:
    session:
      timeout: 30m

spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 30000
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 15
        max-wait: 30000
  freemarker:
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
    max-file-size: 100MB
    max-request-size: 100MB
    enabled: true

medusa:
  packagePath: com.dior.provider
  tableName: bac_logs,xxx,xxx
  author: monster
  mapperSuffix:
  xmlSuffix: classpath:/xml
  baseServiceSwitch: yes
  ftlDirPath: /Users/neo/Desktop/template
  jdbc:
    url: jdbc:mysql://127.0.0.1:3306/cms?autoReconnect=true&useSSL=false
    driver: com.mysql.jdbc.Driver
    username: root
    password:

mycat:
  jdbc:
    url: jdbc:mysql://127.0.0.1:8066/catdb?autoReconnect=true&useSSL=false
    driver: com.mysql.jdbc.Driver
    username: root
    password: 123456