server:
  port: 3315
  servlet:
    session:
      timeout: 30m

spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 30000
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 15
        max-wait: 30000
  freemarker:
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
    max-file-size: 100MB
    max-request-size: 100MB
    enabled: true

medusa:
  #以下三个在使用starter时必须配置
  packagePath: com.xxx.xxx #java目录的根包名称
  mapperSuffix: persistence #mapper文件的包名 -> exp: com.xxx.xxx.persistence
  xmlSuffix: classpath:/xml #xml文件的位置 -> 当前是resources目录下 如果要换为src/main/java目录下则 可以直接写 xml 或 persistence.xml
  #其他的代码生成的可选配置 详细配置请参考medusa.properties
  author: monster #作者名字
  tableName: bac_logs #需要生成的表名 多表时使用逗号分隔
  #  baseServiceSwitch: yes #是否需要生成基础的baseService和baseServiceImpl类 不写则是不生成
  ftlDirPath: /Users/neo/Desktop/template #是否使用ftl模版生成代码 1.路径正确则使用该路径的模版 2.写错路径则使用内置模版 3.不写则使用内置代码模式生成
  jdbc:
    url: jdbc:mysql://127.0.0.1:3306/cms?autoReconnect=true&useSSL=false
    driver: com.mysql.jdbc.Driver
    username: root
    password:
