server:
  port: 3313

miracle:
  jdbc:
    url: jdbc:mysql://localhost:3306/cms?autoReconnect=true
    driver: com.mysql.jdbc.Driver
    username: root
    password:

spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 30000
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 15
        max-wait: 30000

medusa:
  packagePath: com.jy.xxx
  tableName: users, right_roles
  author: monster
  baseServiceSwitch: ok
  ftlDirPath:
  associationColumn: user_id
  jdbc:
      url: jdbc:mysql://localhost:3306/cms?autoReconnect=true
      driver: com.mysql.jdbc.Driver
      username: root
      password: